---
### This task file downloads Nagios-plugins, configures and compiles it
- name: Download the source code for a release of Nagios-plugins and extract it
  unarchive:
    src: "{{ plugin_dwld_url }}"
    dest: "/{{ vm_user }}"
    copy: no
  tags:
    - dwld_nagios_plugin

- name: Configure Nagios-plugins
  command: ./configure
  args:
    chdir: "/{{ vm_user }}/{{ plugin_version }}"
  tags:
    - cfg_nagios_plugin

- name: Compile Nagios-plugins
  command: "{{ item }}"
  args:
    chdir: "/{{ vm_user }}/{{ plugin_version }}"
  with_items:
    - make
    - make install
  tags:
   - cfg_nagios_plugin
