---
- hosts: all
  user: "{{ vm_user }}"
  become: yes
  become_method: sudo
  vars_files:
  - vars/vars.yml
  roles:
    - dependency
    - nagios-core
    - nagios-plugin
    - nrpe
    - configure-nagios
    - add-host